version: '3'

services:
  nodeschool:
    container_name: nodeschool
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./nodeschool:/nodeschool
    working_dir: /nodeschool
    ports:
      - "9564:80"
    command: /bin/bash

    labels:
      - "com.orboan.description=Node.js image with some npm packages installed."
      - "com.orboan.maintainer=Oriol Boan <dev@orboan.com>"
      - "com.orboan.vendor=node.js"
      - "com.orboan.license=GPLv2"

    # Install nvm
    # RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash \ && echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.bashrc \ && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc

    # Keep running bash
    tty: true
    stdin_open: true
